### ISSUE TITLE
Review general

### ISSUE THREAD

**Issue by vr8hub** [BR903/gaston-leroux_the-mystery-of-the-yellow-room_brentanos#1]
- [x] The _Bête du Bon Dieu?_ in chapter 7 should have the question-mark outside the italics. (See [SEMoS 8.2.4](https://standardebooks.org/manual/1.7.0/single-page#8.2.4).)
- [x] The two _Bête Du Bon Dieu_'s in chapter 1 have Du instead of du; there is no reason for it, it's not that way in the rest of the book, nor are they that way in the French original. That seems worthy of standardization in an editorial commit.
- [x] “Temps” is referring to a French newspaper; it should be italicized and semanticated rather than quoted. See [SEMoS 8.2.11.2](https://standardebooks.org/manual/1.7.0/single-page#8.2.11.2). Same for "Matin" and "Epoque."
- [x] The last paragraph in chapter 16 is not part of the diary entry; note the blank line/break between the two, and the reference to Rouletabille in the third person. Interestingly, that is a footnote in the French original.
- [x] Chapter 17's bridgehead is not missing—it's not present in the French original, either.
- [x] I agree with you on the 66f467 commit, and I think maybe the better solution is to create an ignore record for it?
- [x] se.diary just exists so we can semanticate the .dateline; z3998:diary-entry should be used for the diary entries themselves.
- [x] I think the report of the magistrate's examination in ch. 8 should be a blockquote. It is one, so probably should be formatted as one, and then the hr isn't needed at the end. (Which is missing right now; there is a break (blank line) between the report and the "Here the … concluded" in the scans, so it would need an hr if it's not a blockquote.)

**Comment by BR903** [comment]
Thanks; half of these are complete oversights on my part. (I can't believe I never _once_ noticed the inconsistent capitalization on _Bête du Bon Dieu_ in chapter 1. Thank you for catching that!)

I acknowledge that the bridgehead on chapter 17 is also absent in the French original (yes, I also checked at the time) ... but it _clearly_ is supposed to be present. But I've undone the change.

Formatting the magistrate's examination as a blockquote restores the concluding blank line, at the expense of inserting a blank line at the top where none existed. I couldn't decide which was the better route. At the time I chose no blockquote because it also injects indentation, so that seemed slightly less of a change.

**Comment by vr8hub** [comment]
Speaking in broad generalities, we change _appearances_ to match SE's standards (e.g. we only italicize non-English words that aren't in M-W, we put letters in blockquotes whether they're that way in the original or not, we standardize chapter title appeareance, and so on), but we change _content_ (the actual text) very rarely. And most of the "very rarely" is automated in modernize-spelling. We don't re-edit punctuation, etc.

In the case of the magistrate report, that's appearance, and since it _is_ a quote, then it makes sense to format it that way. (We're pretty consistent about that.)

In the case of the bridgehead, that's content. I don't disagree that a case can be made for it's inclusion, but I disagree that it's _clear_—foremost, it's not in the original, and that's pretty definitive all by itself. But, in addition, unlike 16/18, there is a reference to the diary in the first sentence of 17, and that can substitute for the bridgehead. (Yes, 15 has that, too, but it is also the first instance of the diary entries.)

Now, as is obvious, this is all a very inexact science. None of us always get everything "right," where by "right" I mean what Alex would do. :) You are always welcome to ask him.

**Comment by BR903** [comment]
Thanks, these broad generalities are helpful to have in mind.
