### ISSUE TITLE
Review, editorial changes

### ISSUE THREAD

**Issue by vr8hub** [BR903/gaston-leroux_the-mystery-of-the-yellow-room_brentanos#2]
For the editorial changes, we want to correct objective errors (incorrect/missing quotes, dropped letters in words, missing periods, etc.), but in general do not want to change subjective things, i.e. commas we don't like or think should be there (I have concluded that they were paid by the comma in the 18-19th century; the further back you go, the more commas there are), compound words (other than what modernize spelling handles), etc. Those are things for the real editors to decide, and the book's editor has done that. In all cases, we can't change to a word that is not in Merriam-Webster.

- [x] There are non-editorial changes in the b2377b8 (Fix several obvious printer's errors) commit, e.g. all of the `<p></p>` to `<hr>`. We can't mix editorial and non-editorial changes (see  the big yellow box at the beginning of the Step by Step guide), so those will need to be rebased out of this commit.
- [x] Also in the same commit, neither the comma after dawn nor valise are "obvious printer errors."
- [x] For the 865e4ba commit; "devil" is often lowercased (and in fact is elsewhere in the book), light-colo[u]red is not in M-W, so is an invalid change, and the comma after Daddy Jacques is fine as it is. (Two "and"s in a series is quite common, and in this case the first "and" separates the three named people from the unnamed ones that follow. In any case, it's not a printer error.)
- [x] For 828409ab, rung/rang usage in the past is not always perfectly correct (or in the present usage, either, for that matter :)).
- [x] For cd4e5b5; sleight of hand is what's in M-W, and the lack of comma is again an editorial decision, not an error.
- [x] Villanies exists numerous times in our corpus and has reasonable ngram support, although it's not in M-W. I'll ask Alex if he wants to change this throughout or leave it here.

**Comment by BR903** [comment]
Re: "sleight of hand" -- M-W indicates that "sleight of hand" is a noun phrase, but here it is being used as an adjective ("sleight of hand tricks"), so I thought hyphenation was grammatically required? But I'll undo the change.

**Comment by BR903** [comment]
Rebasing finished, including restoring the original spelling of "villanies".
